#!/bin/bash

export RAILS_ENV=production

if [ ! -e "db/GeoLiteCity.dat" ]
then
  echo "Downloading GeoLiteCity.dat"
  curl http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz | gzip -dc > db/GeoLiteCity.dat
fi

bundle install --path vendor/ --binstubs
bundle exec env rake db:migrate

